/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.raiyi.etlModelV2;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LastVisit extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LastVisit\",\"namespace\":\"com.raiyi.etlModelV2\",\"fields\":[{\"name\":\"last_visit_date\",\"type\":\"string\",\"doc\":\"最后一次漫游日期\",\"default\":\"\"},{\"name\":\"last_visit_area\",\"type\":\"string\",\"doc\":\"最后一次漫游地\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 最后一次漫游日期 */
  @Deprecated public java.lang.CharSequence last_visit_date;
  /** 最后一次漫游地 */
  @Deprecated public java.lang.CharSequence last_visit_area;

  /**
   * Default constructor.
   */
  public LastVisit() {}

  /**
   * All-args constructor.
   */
  public LastVisit(java.lang.CharSequence last_visit_date, java.lang.CharSequence last_visit_area) {
    this.last_visit_date = last_visit_date;
    this.last_visit_area = last_visit_area;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return last_visit_date;
    case 1: return last_visit_area;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: last_visit_date = (java.lang.CharSequence)value$; break;
    case 1: last_visit_area = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'last_visit_date' field.
   * 最后一次漫游日期   */
  public java.lang.CharSequence getLastVisitDate() {
    return last_visit_date;
  }

  /**
   * Sets the value of the 'last_visit_date' field.
   * 最后一次漫游日期   * @param value the value to set.
   */
  public void setLastVisitDate(java.lang.CharSequence value) {
    this.last_visit_date = value;
  }

  /**
   * Gets the value of the 'last_visit_area' field.
   * 最后一次漫游地   */
  public java.lang.CharSequence getLastVisitArea() {
    return last_visit_area;
  }

  /**
   * Sets the value of the 'last_visit_area' field.
   * 最后一次漫游地   * @param value the value to set.
   */
  public void setLastVisitArea(java.lang.CharSequence value) {
    this.last_visit_area = value;
  }

  /** Creates a new LastVisit RecordBuilder */
  public static com.raiyi.etlModelV2.LastVisit.Builder newBuilder() {
    return new com.raiyi.etlModelV2.LastVisit.Builder();
  }
  
  /** Creates a new LastVisit RecordBuilder by copying an existing Builder */
  public static com.raiyi.etlModelV2.LastVisit.Builder newBuilder(com.raiyi.etlModelV2.LastVisit.Builder other) {
    return new com.raiyi.etlModelV2.LastVisit.Builder(other);
  }
  
  /** Creates a new LastVisit RecordBuilder by copying an existing LastVisit instance */
  public static com.raiyi.etlModelV2.LastVisit.Builder newBuilder(com.raiyi.etlModelV2.LastVisit other) {
    return new com.raiyi.etlModelV2.LastVisit.Builder(other);
  }
  
  /**
   * RecordBuilder for LastVisit instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LastVisit>
    implements org.apache.avro.data.RecordBuilder<LastVisit> {

    private java.lang.CharSequence last_visit_date;
    private java.lang.CharSequence last_visit_area;

    /** Creates a new Builder */
    private Builder() {
      super(com.raiyi.etlModelV2.LastVisit.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.raiyi.etlModelV2.LastVisit.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing LastVisit instance */
    private Builder(com.raiyi.etlModelV2.LastVisit other) {
            super(com.raiyi.etlModelV2.LastVisit.SCHEMA$);
      if (isValidValue(fields()[0], other.last_visit_date)) {
        this.last_visit_date = data().deepCopy(fields()[0].schema(), other.last_visit_date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.last_visit_area)) {
        this.last_visit_area = data().deepCopy(fields()[1].schema(), other.last_visit_area);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'last_visit_date' field */
    public java.lang.CharSequence getLastVisitDate() {
      return last_visit_date;
    }
    
    /** Sets the value of the 'last_visit_date' field */
    public com.raiyi.etlModelV2.LastVisit.Builder setLastVisitDate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.last_visit_date = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'last_visit_date' field has been set */
    public boolean hasLastVisitDate() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'last_visit_date' field */
    public com.raiyi.etlModelV2.LastVisit.Builder clearLastVisitDate() {
      last_visit_date = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'last_visit_area' field */
    public java.lang.CharSequence getLastVisitArea() {
      return last_visit_area;
    }
    
    /** Sets the value of the 'last_visit_area' field */
    public com.raiyi.etlModelV2.LastVisit.Builder setLastVisitArea(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.last_visit_area = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'last_visit_area' field has been set */
    public boolean hasLastVisitArea() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'last_visit_area' field */
    public com.raiyi.etlModelV2.LastVisit.Builder clearLastVisitArea() {
      last_visit_area = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public LastVisit build() {
      try {
        LastVisit record = new LastVisit();
        record.last_visit_date = fieldSetFlags()[0] ? this.last_visit_date : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.last_visit_area = fieldSetFlags()[1] ? this.last_visit_area : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
