/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DpiResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DpiResult\",\"namespace\":\"model\",\"fields\":[{\"name\":\"phone_number\",\"type\":\"string\"},{\"name\":\"device_id\",\"type\":\"string\"},{\"name\":\"province\",\"type\":\"int\"},{\"name\":\"log_date\",\"type\":\"string\"},{\"name\":\"user_agent\",\"type\":\"string\"},{\"name\":\"host_freq\",\"type\":[{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"HostPair\",\"fields\":[{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"frequency\",\"type\":\"int\"}]}},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence phone_number;
  @Deprecated public java.lang.CharSequence device_id;
  @Deprecated public int province;
  @Deprecated public java.lang.CharSequence log_date;
  @Deprecated public java.lang.CharSequence user_agent;
  @Deprecated public java.util.List<model.HostPair> host_freq;

  /**
   * Default constructor.
   */
  public DpiResult() {}

  /**
   * All-args constructor.
   */
  public DpiResult(java.lang.CharSequence phone_number, java.lang.CharSequence device_id, java.lang.Integer province, java.lang.CharSequence log_date, java.lang.CharSequence user_agent, java.util.List<model.HostPair> host_freq) {
    this.phone_number = phone_number;
    this.device_id = device_id;
    this.province = province;
    this.log_date = log_date;
    this.user_agent = user_agent;
    this.host_freq = host_freq;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return phone_number;
    case 1: return device_id;
    case 2: return province;
    case 3: return log_date;
    case 4: return user_agent;
    case 5: return host_freq;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: phone_number = (java.lang.CharSequence)value$; break;
    case 1: device_id = (java.lang.CharSequence)value$; break;
    case 2: province = (java.lang.Integer)value$; break;
    case 3: log_date = (java.lang.CharSequence)value$; break;
    case 4: user_agent = (java.lang.CharSequence)value$; break;
    case 5: host_freq = (java.util.List<model.HostPair>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'phone_number' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return phone_number;
  }

  /**
   * Sets the value of the 'phone_number' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.phone_number = value;
  }

  /**
   * Gets the value of the 'device_id' field.
   */
  public java.lang.CharSequence getDeviceId() {
    return device_id;
  }

  /**
   * Sets the value of the 'device_id' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.CharSequence value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'province' field.
   */
  public java.lang.Integer getProvince() {
    return province;
  }

  /**
   * Sets the value of the 'province' field.
   * @param value the value to set.
   */
  public void setProvince(java.lang.Integer value) {
    this.province = value;
  }

  /**
   * Gets the value of the 'log_date' field.
   */
  public java.lang.CharSequence getLogDate() {
    return log_date;
  }

  /**
   * Sets the value of the 'log_date' field.
   * @param value the value to set.
   */
  public void setLogDate(java.lang.CharSequence value) {
    this.log_date = value;
  }

  /**
   * Gets the value of the 'user_agent' field.
   */
  public java.lang.CharSequence getUserAgent() {
    return user_agent;
  }

  /**
   * Sets the value of the 'user_agent' field.
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.CharSequence value) {
    this.user_agent = value;
  }

  /**
   * Gets the value of the 'host_freq' field.
   */
  public java.util.List<model.HostPair> getHostFreq() {
    return host_freq;
  }

  /**
   * Sets the value of the 'host_freq' field.
   * @param value the value to set.
   */
  public void setHostFreq(java.util.List<model.HostPair> value) {
    this.host_freq = value;
  }

  /** Creates a new DpiResult RecordBuilder */
  public static model.DpiResult.Builder newBuilder() {
    return new model.DpiResult.Builder();
  }
  
  /** Creates a new DpiResult RecordBuilder by copying an existing Builder */
  public static model.DpiResult.Builder newBuilder(model.DpiResult.Builder other) {
    return new model.DpiResult.Builder(other);
  }
  
  /** Creates a new DpiResult RecordBuilder by copying an existing DpiResult instance */
  public static model.DpiResult.Builder newBuilder(model.DpiResult other) {
    return new model.DpiResult.Builder(other);
  }
  
  /**
   * RecordBuilder for DpiResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DpiResult>
    implements org.apache.avro.data.RecordBuilder<DpiResult> {

    private java.lang.CharSequence phone_number;
    private java.lang.CharSequence device_id;
    private int province;
    private java.lang.CharSequence log_date;
    private java.lang.CharSequence user_agent;
    private java.util.List<model.HostPair> host_freq;

    /** Creates a new Builder */
    private Builder() {
      super(model.DpiResult.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(model.DpiResult.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing DpiResult instance */
    private Builder(model.DpiResult other) {
            super(model.DpiResult.SCHEMA$);
      if (isValidValue(fields()[0], other.phone_number)) {
        this.phone_number = data().deepCopy(fields()[0].schema(), other.phone_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.device_id)) {
        this.device_id = data().deepCopy(fields()[1].schema(), other.device_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.province)) {
        this.province = data().deepCopy(fields()[2].schema(), other.province);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.log_date)) {
        this.log_date = data().deepCopy(fields()[3].schema(), other.log_date);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.user_agent)) {
        this.user_agent = data().deepCopy(fields()[4].schema(), other.user_agent);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.host_freq)) {
        this.host_freq = data().deepCopy(fields()[5].schema(), other.host_freq);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'phone_number' field */
    public java.lang.CharSequence getPhoneNumber() {
      return phone_number;
    }
    
    /** Sets the value of the 'phone_number' field */
    public model.DpiResult.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.phone_number = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'phone_number' field has been set */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'phone_number' field */
    public model.DpiResult.Builder clearPhoneNumber() {
      phone_number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'device_id' field */
    public java.lang.CharSequence getDeviceId() {
      return device_id;
    }
    
    /** Sets the value of the 'device_id' field */
    public model.DpiResult.Builder setDeviceId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.device_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'device_id' field has been set */
    public boolean hasDeviceId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'device_id' field */
    public model.DpiResult.Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'province' field */
    public java.lang.Integer getProvince() {
      return province;
    }
    
    /** Sets the value of the 'province' field */
    public model.DpiResult.Builder setProvince(int value) {
      validate(fields()[2], value);
      this.province = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'province' field has been set */
    public boolean hasProvince() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'province' field */
    public model.DpiResult.Builder clearProvince() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'log_date' field */
    public java.lang.CharSequence getLogDate() {
      return log_date;
    }
    
    /** Sets the value of the 'log_date' field */
    public model.DpiResult.Builder setLogDate(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.log_date = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'log_date' field has been set */
    public boolean hasLogDate() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'log_date' field */
    public model.DpiResult.Builder clearLogDate() {
      log_date = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'user_agent' field */
    public java.lang.CharSequence getUserAgent() {
      return user_agent;
    }
    
    /** Sets the value of the 'user_agent' field */
    public model.DpiResult.Builder setUserAgent(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.user_agent = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'user_agent' field has been set */
    public boolean hasUserAgent() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'user_agent' field */
    public model.DpiResult.Builder clearUserAgent() {
      user_agent = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'host_freq' field */
    public java.util.List<model.HostPair> getHostFreq() {
      return host_freq;
    }
    
    /** Sets the value of the 'host_freq' field */
    public model.DpiResult.Builder setHostFreq(java.util.List<model.HostPair> value) {
      validate(fields()[5], value);
      this.host_freq = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'host_freq' field has been set */
    public boolean hasHostFreq() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'host_freq' field */
    public model.DpiResult.Builder clearHostFreq() {
      host_freq = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public DpiResult build() {
      try {
        DpiResult record = new DpiResult();
        record.phone_number = fieldSetFlags()[0] ? this.phone_number : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.device_id = fieldSetFlags()[1] ? this.device_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.province = fieldSetFlags()[2] ? this.province : (java.lang.Integer) defaultValue(fields()[2]);
        record.log_date = fieldSetFlags()[3] ? this.log_date : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.user_agent = fieldSetFlags()[4] ? this.user_agent : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.host_freq = fieldSetFlags()[5] ? this.host_freq : (java.util.List<model.HostPair>) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
