/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.raiyi.etlModel;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Complaint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Complaint\",\"namespace\":\"com.raiyi.etlModel\",\"fields\":[{\"name\":\"call_from_tele\",\"type\":\"int\",\"doc\":\"10000主叫次数\",\"default\":-1},{\"name\":\"call_to_tele\",\"type\":\"int\",\"doc\":\"10000被叫次数\",\"default\":-1},{\"name\":\"call_to_MIT\",\"type\":\"int\",\"doc\":\"12300次数\",\"default\":-1},{\"name\":\"call_to_sms\",\"type\":\"int\",\"doc\":\"12321垃圾短信投诉次数\",\"default\":-1}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 10000主叫次数 */
  @Deprecated public int call_from_tele;
  /** 10000被叫次数 */
  @Deprecated public int call_to_tele;
  /** 12300次数 */
  @Deprecated public int call_to_MIT;
  /** 12321垃圾短信投诉次数 */
  @Deprecated public int call_to_sms;

  /**
   * Default constructor.
   */
  public Complaint() {}

  /**
   * All-args constructor.
   */
  public Complaint(java.lang.Integer call_from_tele, java.lang.Integer call_to_tele, java.lang.Integer call_to_MIT, java.lang.Integer call_to_sms) {
    this.call_from_tele = call_from_tele;
    this.call_to_tele = call_to_tele;
    this.call_to_MIT = call_to_MIT;
    this.call_to_sms = call_to_sms;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return call_from_tele;
    case 1: return call_to_tele;
    case 2: return call_to_MIT;
    case 3: return call_to_sms;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: call_from_tele = (java.lang.Integer)value$; break;
    case 1: call_to_tele = (java.lang.Integer)value$; break;
    case 2: call_to_MIT = (java.lang.Integer)value$; break;
    case 3: call_to_sms = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'call_from_tele' field.
   * 10000主叫次数   */
  public java.lang.Integer getCallFromTele() {
    return call_from_tele;
  }

  /**
   * Sets the value of the 'call_from_tele' field.
   * 10000主叫次数   * @param value the value to set.
   */
  public void setCallFromTele(java.lang.Integer value) {
    this.call_from_tele = value;
  }

  /**
   * Gets the value of the 'call_to_tele' field.
   * 10000被叫次数   */
  public java.lang.Integer getCallToTele() {
    return call_to_tele;
  }

  /**
   * Sets the value of the 'call_to_tele' field.
   * 10000被叫次数   * @param value the value to set.
   */
  public void setCallToTele(java.lang.Integer value) {
    this.call_to_tele = value;
  }

  /**
   * Gets the value of the 'call_to_MIT' field.
   * 12300次数   */
  public java.lang.Integer getCallToMIT() {
    return call_to_MIT;
  }

  /**
   * Sets the value of the 'call_to_MIT' field.
   * 12300次数   * @param value the value to set.
   */
  public void setCallToMIT(java.lang.Integer value) {
    this.call_to_MIT = value;
  }

  /**
   * Gets the value of the 'call_to_sms' field.
   * 12321垃圾短信投诉次数   */
  public java.lang.Integer getCallToSms() {
    return call_to_sms;
  }

  /**
   * Sets the value of the 'call_to_sms' field.
   * 12321垃圾短信投诉次数   * @param value the value to set.
   */
  public void setCallToSms(java.lang.Integer value) {
    this.call_to_sms = value;
  }

  /** Creates a new Complaint RecordBuilder */
  public static com.raiyi.etlModel.Complaint.Builder newBuilder() {
    return new com.raiyi.etlModel.Complaint.Builder();
  }
  
  /** Creates a new Complaint RecordBuilder by copying an existing Builder */
  public static com.raiyi.etlModel.Complaint.Builder newBuilder(com.raiyi.etlModel.Complaint.Builder other) {
    return new com.raiyi.etlModel.Complaint.Builder(other);
  }
  
  /** Creates a new Complaint RecordBuilder by copying an existing Complaint instance */
  public static com.raiyi.etlModel.Complaint.Builder newBuilder(com.raiyi.etlModel.Complaint other) {
    return new com.raiyi.etlModel.Complaint.Builder(other);
  }
  
  /**
   * RecordBuilder for Complaint instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Complaint>
    implements org.apache.avro.data.RecordBuilder<Complaint> {

    private int call_from_tele;
    private int call_to_tele;
    private int call_to_MIT;
    private int call_to_sms;

    /** Creates a new Builder */
    private Builder() {
      super(com.raiyi.etlModel.Complaint.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.raiyi.etlModel.Complaint.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Complaint instance */
    private Builder(com.raiyi.etlModel.Complaint other) {
            super(com.raiyi.etlModel.Complaint.SCHEMA$);
      if (isValidValue(fields()[0], other.call_from_tele)) {
        this.call_from_tele = data().deepCopy(fields()[0].schema(), other.call_from_tele);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.call_to_tele)) {
        this.call_to_tele = data().deepCopy(fields()[1].schema(), other.call_to_tele);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.call_to_MIT)) {
        this.call_to_MIT = data().deepCopy(fields()[2].schema(), other.call_to_MIT);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.call_to_sms)) {
        this.call_to_sms = data().deepCopy(fields()[3].schema(), other.call_to_sms);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'call_from_tele' field */
    public java.lang.Integer getCallFromTele() {
      return call_from_tele;
    }
    
    /** Sets the value of the 'call_from_tele' field */
    public com.raiyi.etlModel.Complaint.Builder setCallFromTele(int value) {
      validate(fields()[0], value);
      this.call_from_tele = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'call_from_tele' field has been set */
    public boolean hasCallFromTele() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'call_from_tele' field */
    public com.raiyi.etlModel.Complaint.Builder clearCallFromTele() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'call_to_tele' field */
    public java.lang.Integer getCallToTele() {
      return call_to_tele;
    }
    
    /** Sets the value of the 'call_to_tele' field */
    public com.raiyi.etlModel.Complaint.Builder setCallToTele(int value) {
      validate(fields()[1], value);
      this.call_to_tele = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'call_to_tele' field has been set */
    public boolean hasCallToTele() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'call_to_tele' field */
    public com.raiyi.etlModel.Complaint.Builder clearCallToTele() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'call_to_MIT' field */
    public java.lang.Integer getCallToMIT() {
      return call_to_MIT;
    }
    
    /** Sets the value of the 'call_to_MIT' field */
    public com.raiyi.etlModel.Complaint.Builder setCallToMIT(int value) {
      validate(fields()[2], value);
      this.call_to_MIT = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'call_to_MIT' field has been set */
    public boolean hasCallToMIT() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'call_to_MIT' field */
    public com.raiyi.etlModel.Complaint.Builder clearCallToMIT() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'call_to_sms' field */
    public java.lang.Integer getCallToSms() {
      return call_to_sms;
    }
    
    /** Sets the value of the 'call_to_sms' field */
    public com.raiyi.etlModel.Complaint.Builder setCallToSms(int value) {
      validate(fields()[3], value);
      this.call_to_sms = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'call_to_sms' field has been set */
    public boolean hasCallToSms() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'call_to_sms' field */
    public com.raiyi.etlModel.Complaint.Builder clearCallToSms() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Complaint build() {
      try {
        Complaint record = new Complaint();
        record.call_from_tele = fieldSetFlags()[0] ? this.call_from_tele : (java.lang.Integer) defaultValue(fields()[0]);
        record.call_to_tele = fieldSetFlags()[1] ? this.call_to_tele : (java.lang.Integer) defaultValue(fields()[1]);
        record.call_to_MIT = fieldSetFlags()[2] ? this.call_to_MIT : (java.lang.Integer) defaultValue(fields()[2]);
        record.call_to_sms = fieldSetFlags()[3] ? this.call_to_sms : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
