/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.raiyi.modelV2;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ProvOfferId extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProvOfferId\",\"namespace\":\"com.raiyi.modelV2\",\"fields\":[{\"name\":\"offer_id_1\",\"type\":\"string\",\"doc\":\"套餐ID1\",\"default\":\"\"},{\"name\":\"offer_id_2\",\"type\":\"string\",\"doc\":\"套餐ID2\",\"default\":\"\"},{\"name\":\"offer_id_3\",\"type\":\"string\",\"doc\":\"套餐ID3\",\"default\":\"\"},{\"name\":\"offer_id_4\",\"type\":\"string\",\"doc\":\"套餐ID4\",\"default\":\"\"},{\"name\":\"offer_id_5\",\"type\":\"string\",\"doc\":\"套餐ID5\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 套餐ID1 */
  @Deprecated public java.lang.CharSequence offer_id_1;
  /** 套餐ID2 */
  @Deprecated public java.lang.CharSequence offer_id_2;
  /** 套餐ID3 */
  @Deprecated public java.lang.CharSequence offer_id_3;
  /** 套餐ID4 */
  @Deprecated public java.lang.CharSequence offer_id_4;
  /** 套餐ID5 */
  @Deprecated public java.lang.CharSequence offer_id_5;

  /**
   * Default constructor.
   */
  public ProvOfferId() {}

  /**
   * All-args constructor.
   */
  public ProvOfferId(java.lang.CharSequence offer_id_1, java.lang.CharSequence offer_id_2, java.lang.CharSequence offer_id_3, java.lang.CharSequence offer_id_4, java.lang.CharSequence offer_id_5) {
    this.offer_id_1 = offer_id_1;
    this.offer_id_2 = offer_id_2;
    this.offer_id_3 = offer_id_3;
    this.offer_id_4 = offer_id_4;
    this.offer_id_5 = offer_id_5;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return offer_id_1;
    case 1: return offer_id_2;
    case 2: return offer_id_3;
    case 3: return offer_id_4;
    case 4: return offer_id_5;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: offer_id_1 = (java.lang.CharSequence)value$; break;
    case 1: offer_id_2 = (java.lang.CharSequence)value$; break;
    case 2: offer_id_3 = (java.lang.CharSequence)value$; break;
    case 3: offer_id_4 = (java.lang.CharSequence)value$; break;
    case 4: offer_id_5 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'offer_id_1' field.
   * 套餐ID1   */
  public java.lang.CharSequence getOfferId1() {
    return offer_id_1;
  }

  /**
   * Sets the value of the 'offer_id_1' field.
   * 套餐ID1   * @param value the value to set.
   */
  public void setOfferId1(java.lang.CharSequence value) {
    this.offer_id_1 = value;
  }

  /**
   * Gets the value of the 'offer_id_2' field.
   * 套餐ID2   */
  public java.lang.CharSequence getOfferId2() {
    return offer_id_2;
  }

  /**
   * Sets the value of the 'offer_id_2' field.
   * 套餐ID2   * @param value the value to set.
   */
  public void setOfferId2(java.lang.CharSequence value) {
    this.offer_id_2 = value;
  }

  /**
   * Gets the value of the 'offer_id_3' field.
   * 套餐ID3   */
  public java.lang.CharSequence getOfferId3() {
    return offer_id_3;
  }

  /**
   * Sets the value of the 'offer_id_3' field.
   * 套餐ID3   * @param value the value to set.
   */
  public void setOfferId3(java.lang.CharSequence value) {
    this.offer_id_3 = value;
  }

  /**
   * Gets the value of the 'offer_id_4' field.
   * 套餐ID4   */
  public java.lang.CharSequence getOfferId4() {
    return offer_id_4;
  }

  /**
   * Sets the value of the 'offer_id_4' field.
   * 套餐ID4   * @param value the value to set.
   */
  public void setOfferId4(java.lang.CharSequence value) {
    this.offer_id_4 = value;
  }

  /**
   * Gets the value of the 'offer_id_5' field.
   * 套餐ID5   */
  public java.lang.CharSequence getOfferId5() {
    return offer_id_5;
  }

  /**
   * Sets the value of the 'offer_id_5' field.
   * 套餐ID5   * @param value the value to set.
   */
  public void setOfferId5(java.lang.CharSequence value) {
    this.offer_id_5 = value;
  }

  /** Creates a new ProvOfferId RecordBuilder */
  public static com.raiyi.modelV2.ProvOfferId.Builder newBuilder() {
    return new com.raiyi.modelV2.ProvOfferId.Builder();
  }
  
  /** Creates a new ProvOfferId RecordBuilder by copying an existing Builder */
  public static com.raiyi.modelV2.ProvOfferId.Builder newBuilder(com.raiyi.modelV2.ProvOfferId.Builder other) {
    return new com.raiyi.modelV2.ProvOfferId.Builder(other);
  }
  
  /** Creates a new ProvOfferId RecordBuilder by copying an existing ProvOfferId instance */
  public static com.raiyi.modelV2.ProvOfferId.Builder newBuilder(com.raiyi.modelV2.ProvOfferId other) {
    return new com.raiyi.modelV2.ProvOfferId.Builder(other);
  }
  
  /**
   * RecordBuilder for ProvOfferId instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProvOfferId>
    implements org.apache.avro.data.RecordBuilder<ProvOfferId> {

    private java.lang.CharSequence offer_id_1;
    private java.lang.CharSequence offer_id_2;
    private java.lang.CharSequence offer_id_3;
    private java.lang.CharSequence offer_id_4;
    private java.lang.CharSequence offer_id_5;

    /** Creates a new Builder */
    private Builder() {
      super(com.raiyi.modelV2.ProvOfferId.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.raiyi.modelV2.ProvOfferId.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing ProvOfferId instance */
    private Builder(com.raiyi.modelV2.ProvOfferId other) {
            super(com.raiyi.modelV2.ProvOfferId.SCHEMA$);
      if (isValidValue(fields()[0], other.offer_id_1)) {
        this.offer_id_1 = data().deepCopy(fields()[0].schema(), other.offer_id_1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.offer_id_2)) {
        this.offer_id_2 = data().deepCopy(fields()[1].schema(), other.offer_id_2);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.offer_id_3)) {
        this.offer_id_3 = data().deepCopy(fields()[2].schema(), other.offer_id_3);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.offer_id_4)) {
        this.offer_id_4 = data().deepCopy(fields()[3].schema(), other.offer_id_4);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.offer_id_5)) {
        this.offer_id_5 = data().deepCopy(fields()[4].schema(), other.offer_id_5);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'offer_id_1' field */
    public java.lang.CharSequence getOfferId1() {
      return offer_id_1;
    }
    
    /** Sets the value of the 'offer_id_1' field */
    public com.raiyi.modelV2.ProvOfferId.Builder setOfferId1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.offer_id_1 = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'offer_id_1' field has been set */
    public boolean hasOfferId1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'offer_id_1' field */
    public com.raiyi.modelV2.ProvOfferId.Builder clearOfferId1() {
      offer_id_1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'offer_id_2' field */
    public java.lang.CharSequence getOfferId2() {
      return offer_id_2;
    }
    
    /** Sets the value of the 'offer_id_2' field */
    public com.raiyi.modelV2.ProvOfferId.Builder setOfferId2(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.offer_id_2 = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'offer_id_2' field has been set */
    public boolean hasOfferId2() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'offer_id_2' field */
    public com.raiyi.modelV2.ProvOfferId.Builder clearOfferId2() {
      offer_id_2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'offer_id_3' field */
    public java.lang.CharSequence getOfferId3() {
      return offer_id_3;
    }
    
    /** Sets the value of the 'offer_id_3' field */
    public com.raiyi.modelV2.ProvOfferId.Builder setOfferId3(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.offer_id_3 = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'offer_id_3' field has been set */
    public boolean hasOfferId3() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'offer_id_3' field */
    public com.raiyi.modelV2.ProvOfferId.Builder clearOfferId3() {
      offer_id_3 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'offer_id_4' field */
    public java.lang.CharSequence getOfferId4() {
      return offer_id_4;
    }
    
    /** Sets the value of the 'offer_id_4' field */
    public com.raiyi.modelV2.ProvOfferId.Builder setOfferId4(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.offer_id_4 = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'offer_id_4' field has been set */
    public boolean hasOfferId4() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'offer_id_4' field */
    public com.raiyi.modelV2.ProvOfferId.Builder clearOfferId4() {
      offer_id_4 = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'offer_id_5' field */
    public java.lang.CharSequence getOfferId5() {
      return offer_id_5;
    }
    
    /** Sets the value of the 'offer_id_5' field */
    public com.raiyi.modelV2.ProvOfferId.Builder setOfferId5(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.offer_id_5 = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'offer_id_5' field has been set */
    public boolean hasOfferId5() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'offer_id_5' field */
    public com.raiyi.modelV2.ProvOfferId.Builder clearOfferId5() {
      offer_id_5 = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public ProvOfferId build() {
      try {
        ProvOfferId record = new ProvOfferId();
        record.offer_id_1 = fieldSetFlags()[0] ? this.offer_id_1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.offer_id_2 = fieldSetFlags()[1] ? this.offer_id_2 : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.offer_id_3 = fieldSetFlags()[2] ? this.offer_id_3 : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.offer_id_4 = fieldSetFlags()[3] ? this.offer_id_4 : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.offer_id_5 = fieldSetFlags()[4] ? this.offer_id_5 : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
